---
- name: create service dir
  file:
    path: "/etc/systemd/system/postgresql.service.d"
    state: directory
    mode: 0755

- name: place override.conf
  template:
    src: systemd-override.j2
    dest: "/etc/systemd/system/postgresql.service.d/override.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload postgresql unit

- name: create directory {{ templates_dir }}/postgresql
  file:
    path: "{{ templates_dir }}/postgresql"
    state: directory
    owner: "root"
    group: "root"

- name: place inital-setup script
  template:
    src: initial-setup.j2
    dest: "{{ templates_dir }}/postgresql/initial-setup"
    owner: "root"
    group: "root"
    mode: 0750
