---

- name: Install Python modules via apt
  apt:
    name: "{{ postgresql_python_modules_apt }}"
    state: present

- name: Install Python modules via pip
  pip:
    name: "{{ postgresql_python_modules_pip }}"
    state: present
    executable: pip3

- name: Ensure PostgreSQL packages are installed
  apt:
    name: "{{ postgresql_packages }}"
    state: present

- name: Ensure psycopg2-binary is installed
  pip:
    name: psycopg2-binary
    state: present
    executable: pip3

- name: Ensure all configured locales are present
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_locales }}"
  notify: restart postgresql service

- name: Force-restart PostgreSQL after new locales are generated
  meta: flush_handlers
