---

- name: Ensure needed Python modules are installed
  apt:
    state: present
    name:
      - python-setuptools
      - python3-pip

- name: Ensure psycopg2-binary is installed
  pip:
    name: psycopg2-binary
    state: present
    executable: pip3

- name: Ensure PostgreSQL packages are installed
  apt:
    name: "{{ postgresql_packages }}"
    state: present

- name: Ensure all configured locales are present
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_locales }}"
  notify: restart postgresql service

- name: Force-restart PostgreSQL after new locales are generated
  meta: flush_handlers
